// Code generated by counterfeiter. DO NOT EDIT.
package protoplaygroundfakes

import (
	"sync"

	"github.com/ThreeDotsLabs/watermill/message"
	"github.com/marchmiel/proto-playground/clientTools"
)

type FakePubSubConnector struct {
	GetConnTypeStub        func() string
	getConnTypeMutex       sync.RWMutex
	getConnTypeArgsForCall []struct {
	}
	getConnTypeReturns struct {
		result1 string
	}
	getConnTypeReturnsOnCall map[int]struct {
		result1 string
	}
	GetSubNameStub        func() string
	getSubNameMutex       sync.RWMutex
	getSubNameArgsForCall []struct {
	}
	getSubNameReturns struct {
		result1 string
	}
	getSubNameReturnsOnCall map[int]struct {
		result1 string
	}
	SendReservationStub        func(*message.Message) (<-chan *message.Message, error)
	sendReservationMutex       sync.RWMutex
	sendReservationArgsForCall []struct {
		arg1 *message.Message
	}
	sendReservationReturns struct {
		result1 <-chan *message.Message
		result2 error
	}
	sendReservationReturnsOnCall map[int]struct {
		result1 <-chan *message.Message
		result2 error
	}
	SetConnTypeStub        func(string)
	setConnTypeMutex       sync.RWMutex
	setConnTypeArgsForCall []struct {
		arg1 string
	}
	SetSubNameStub        func(string)
	setSubNameMutex       sync.RWMutex
	setSubNameArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePubSubConnector) GetConnType() string {
	fake.getConnTypeMutex.Lock()
	ret, specificReturn := fake.getConnTypeReturnsOnCall[len(fake.getConnTypeArgsForCall)]
	fake.getConnTypeArgsForCall = append(fake.getConnTypeArgsForCall, struct {
	}{})
	fake.recordInvocation("GetConnType", []interface{}{})
	fake.getConnTypeMutex.Unlock()
	if fake.GetConnTypeStub != nil {
		return fake.GetConnTypeStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.getConnTypeReturns
	return fakeReturns.result1
}

func (fake *FakePubSubConnector) GetConnTypeCallCount() int {
	fake.getConnTypeMutex.RLock()
	defer fake.getConnTypeMutex.RUnlock()
	return len(fake.getConnTypeArgsForCall)
}

func (fake *FakePubSubConnector) GetConnTypeCalls(stub func() string) {
	fake.getConnTypeMutex.Lock()
	defer fake.getConnTypeMutex.Unlock()
	fake.GetConnTypeStub = stub
}

func (fake *FakePubSubConnector) GetConnTypeReturns(result1 string) {
	fake.getConnTypeMutex.Lock()
	defer fake.getConnTypeMutex.Unlock()
	fake.GetConnTypeStub = nil
	fake.getConnTypeReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakePubSubConnector) GetConnTypeReturnsOnCall(i int, result1 string) {
	fake.getConnTypeMutex.Lock()
	defer fake.getConnTypeMutex.Unlock()
	fake.GetConnTypeStub = nil
	if fake.getConnTypeReturnsOnCall == nil {
		fake.getConnTypeReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getConnTypeReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakePubSubConnector) GetSubName() string {
	fake.getSubNameMutex.Lock()
	ret, specificReturn := fake.getSubNameReturnsOnCall[len(fake.getSubNameArgsForCall)]
	fake.getSubNameArgsForCall = append(fake.getSubNameArgsForCall, struct {
	}{})
	fake.recordInvocation("GetSubName", []interface{}{})
	fake.getSubNameMutex.Unlock()
	if fake.GetSubNameStub != nil {
		return fake.GetSubNameStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.getSubNameReturns
	return fakeReturns.result1
}

func (fake *FakePubSubConnector) GetSubNameCallCount() int {
	fake.getSubNameMutex.RLock()
	defer fake.getSubNameMutex.RUnlock()
	return len(fake.getSubNameArgsForCall)
}

func (fake *FakePubSubConnector) GetSubNameCalls(stub func() string) {
	fake.getSubNameMutex.Lock()
	defer fake.getSubNameMutex.Unlock()
	fake.GetSubNameStub = stub
}

func (fake *FakePubSubConnector) GetSubNameReturns(result1 string) {
	fake.getSubNameMutex.Lock()
	defer fake.getSubNameMutex.Unlock()
	fake.GetSubNameStub = nil
	fake.getSubNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakePubSubConnector) GetSubNameReturnsOnCall(i int, result1 string) {
	fake.getSubNameMutex.Lock()
	defer fake.getSubNameMutex.Unlock()
	fake.GetSubNameStub = nil
	if fake.getSubNameReturnsOnCall == nil {
		fake.getSubNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getSubNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakePubSubConnector) SendReservation(arg1 *message.Message) (<-chan *message.Message, error) {
	fake.sendReservationMutex.Lock()
	ret, specificReturn := fake.sendReservationReturnsOnCall[len(fake.sendReservationArgsForCall)]
	fake.sendReservationArgsForCall = append(fake.sendReservationArgsForCall, struct {
		arg1 *message.Message
	}{arg1})
	fake.recordInvocation("SendReservation", []interface{}{arg1})
	fake.sendReservationMutex.Unlock()
	if fake.SendReservationStub != nil {
		return fake.SendReservationStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.sendReservationReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePubSubConnector) SendReservationCallCount() int {
	fake.sendReservationMutex.RLock()
	defer fake.sendReservationMutex.RUnlock()
	return len(fake.sendReservationArgsForCall)
}

func (fake *FakePubSubConnector) SendReservationCalls(stub func(*message.Message) (<-chan *message.Message, error)) {
	fake.sendReservationMutex.Lock()
	defer fake.sendReservationMutex.Unlock()
	fake.SendReservationStub = stub
}

func (fake *FakePubSubConnector) SendReservationArgsForCall(i int) *message.Message {
	fake.sendReservationMutex.RLock()
	defer fake.sendReservationMutex.RUnlock()
	argsForCall := fake.sendReservationArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePubSubConnector) SendReservationReturns(result1 <-chan *message.Message, result2 error) {
	fake.sendReservationMutex.Lock()
	defer fake.sendReservationMutex.Unlock()
	fake.SendReservationStub = nil
	fake.sendReservationReturns = struct {
		result1 <-chan *message.Message
		result2 error
	}{result1, result2}
}

func (fake *FakePubSubConnector) SendReservationReturnsOnCall(i int, result1 <-chan *message.Message, result2 error) {
	fake.sendReservationMutex.Lock()
	defer fake.sendReservationMutex.Unlock()
	fake.SendReservationStub = nil
	if fake.sendReservationReturnsOnCall == nil {
		fake.sendReservationReturnsOnCall = make(map[int]struct {
			result1 <-chan *message.Message
			result2 error
		})
	}
	fake.sendReservationReturnsOnCall[i] = struct {
		result1 <-chan *message.Message
		result2 error
	}{result1, result2}
}

func (fake *FakePubSubConnector) SetConnType(arg1 string) {
	fake.setConnTypeMutex.Lock()
	fake.setConnTypeArgsForCall = append(fake.setConnTypeArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("SetConnType", []interface{}{arg1})
	fake.setConnTypeMutex.Unlock()
	if fake.SetConnTypeStub != nil {
		fake.SetConnTypeStub(arg1)
	}
}

func (fake *FakePubSubConnector) SetConnTypeCallCount() int {
	fake.setConnTypeMutex.RLock()
	defer fake.setConnTypeMutex.RUnlock()
	return len(fake.setConnTypeArgsForCall)
}

func (fake *FakePubSubConnector) SetConnTypeCalls(stub func(string)) {
	fake.setConnTypeMutex.Lock()
	defer fake.setConnTypeMutex.Unlock()
	fake.SetConnTypeStub = stub
}

func (fake *FakePubSubConnector) SetConnTypeArgsForCall(i int) string {
	fake.setConnTypeMutex.RLock()
	defer fake.setConnTypeMutex.RUnlock()
	argsForCall := fake.setConnTypeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePubSubConnector) SetSubName(arg1 string) {
	fake.setSubNameMutex.Lock()
	fake.setSubNameArgsForCall = append(fake.setSubNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("SetSubName", []interface{}{arg1})
	fake.setSubNameMutex.Unlock()
	if fake.SetSubNameStub != nil {
		fake.SetSubNameStub(arg1)
	}
}

func (fake *FakePubSubConnector) SetSubNameCallCount() int {
	fake.setSubNameMutex.RLock()
	defer fake.setSubNameMutex.RUnlock()
	return len(fake.setSubNameArgsForCall)
}

func (fake *FakePubSubConnector) SetSubNameCalls(stub func(string)) {
	fake.setSubNameMutex.Lock()
	defer fake.setSubNameMutex.Unlock()
	fake.SetSubNameStub = stub
}

func (fake *FakePubSubConnector) SetSubNameArgsForCall(i int) string {
	fake.setSubNameMutex.RLock()
	defer fake.setSubNameMutex.RUnlock()
	argsForCall := fake.setSubNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePubSubConnector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getConnTypeMutex.RLock()
	defer fake.getConnTypeMutex.RUnlock()
	fake.getSubNameMutex.RLock()
	defer fake.getSubNameMutex.RUnlock()
	fake.sendReservationMutex.RLock()
	defer fake.sendReservationMutex.RUnlock()
	fake.setConnTypeMutex.RLock()
	defer fake.setConnTypeMutex.RUnlock()
	fake.setSubNameMutex.RLock()
	defer fake.setSubNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePubSubConnector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ clientTools.PubSubConnector = new(FakePubSubConnector)
